# -*- coding: utf-8 -*-
"""SMSSpamCollection - Multinomial Naive Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qn8Juwh6-78srXgaA-PmiHto1bwos3gf
"""

!pip install nltk

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

nltk.download('stopwords')

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("spam.csv", encoding="latin-1")

df.head()

df = df[['v1','v2']]

df.columns = ['label','message']

df.head()

print(df.info())

print(df['label'].value_counts())

plt.figure(figsize=(6,4))

df['label'].value_counts().plot(kind='bar')

plt.title("SMS Categories")

plt.xlabel("Class")

plt.ylabel("Count")

plt.show()

df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

df.head()

stemmer = PorterStemmer()

stop_words = set(stopwords.words('english'))

def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()

    words = [
        stemmer.stem(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

df['clean_message'] = df['message'].apply(clean_text)

df.head()

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df['clean_message'])

y = df['label']

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.2,

    random_state=42

)

model = MultinomialNB()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)

print("Accuracy :",accuracy)

print(classification_report(y_test,y_pred))

cm = confusion_matrix(y_test,y_pred)

disp = ConfusionMatrixDisplay(

    confusion_matrix=cm,

    display_labels=['Ham','Spam']

)

disp.plot()

plt.show()

sms = ["Congratulations! You have won a free iPhone. Click the link now."]

sms_clean = [clean_text(s) for s in sms]

sms_vector = vectorizer.transform(sms_clean)

prediction = model.predict(sms_vector)

if prediction[0] == 1:
    print("Spam / Phishing SMS")
else:
    print("Legitimate SMS")

messages = [

    "Meeting is at 2 PM tomorrow.",

    "URGENT! Your bank account has been suspended. Verify now.",

    "Happy Birthday Justin!",

    "Claim your lottery prize immediately."

]

for msg in messages:

    cleaned = clean_text(msg)

    vector = vectorizer.transform([cleaned])

    pred = model.predict(vector)

    if pred[0] == 1:
        print(msg)
        print("Prediction : Spam\n")

    else:
        print(msg)
        print("Prediction : Legitimate\n")

import pickle

pickle.dump(model,open("sms_model.pkl","wb"))

pickle.dump(vectorizer,open("tfidf.pkl","wb"))

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print(f"Accuracy: {accuracy*100:.2f}%")

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                              display_labels=["Ham","Spam"])

disp.plot()

plt.show()

from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test)[:,1]

auc = roc_auc_score(y_test, y_prob)

print(f"ROC-AUC Score: {auc:.4f}")

from sklearn.metrics import precision_score, recall_score, f1_score

print(f"Accuracy : {accuracy_score(y_test,y_pred)*100:.2f}%")
print(f"Precision: {precision_score(y_test,y_pred)*100:.2f}%")
print(f"Recall   : {recall_score(y_test,y_pred)*100:.2f}%")
print(f"F1 Score : {f1_score(y_test,y_pred)*100:.2f}%")